# Generated by Django 4.1.7 on 2023-04-05 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score',
            new_name='value',
        ),
    ]
