# Generated by Django 4.1.7 on 2023-04-05 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_alter_score_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='user',
            new_name='player',
        ),
    ]
